name: MD to HTML
  
on:
   push:
     branches:
       - main
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.x'

      - name: Install dependencies
        run: pip install markdown2

      - name: MD to HTML
        run: |
              echo "$PWD"
              cd docs
              ls
              mkdir -p docs
              python scripts/main.py

      - name: Commit and push
        run: |
             git config --global user.name "github-actions"
             git config --global user.email "github-actions@github.com"
             git add docs
             git add -A
             git commit -m "Updating pages" || echo "no changes to be made"
             git push
        
